/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Pet = {
  /**
   * @format int64
   */
  id: number;
  name: string;
  tag?: string;
};

/**
 * @maxItems 100
 */
export type Pets = Pet[];

export type Error = {
  /**
   * @format int32
   */
  code: number;
  message: string;
};
